### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by MagaTailor** [serde-rs/syntex#28]
I've noticed this is the only crate in the ecosystem that makes rustc's memory usage go through the roof during compilation. (especially bad in rust-bindgen or it's just the recent rustc)

That makes it difficult and slow to compile on a 1GB arm board even with ZRAM swap enabled.

What say ye?

**Comment by erickt** [comment]
syntex is essentially the Rust frontend that I've extracted, and in order to make it easy to track, we'd have to address memory issues in [rust-lang/rust](https://github.com/rust-lang/rust)'s libsyntax, which we'd then pick up over here. So unfortunately I'd be quite non-trivial to get it to use less memory. Could you file a ticket in that repository instead, especially if you've got an easy-to-reproduce example? That'd really help.

**Comment by MagaTailor** [comment]
I have no idea how to narrow it down so I'll let it slide for now.
